# This Docker Compose file enables you to test if all services are running well before switching to production
# 
services:
  client:
    image: client-img
    container_name: client-cont
    build:
      context: ./client
      dockerfile: stage.Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - flask_vue_network
    command: ["http-server", "dist", "-p", "8000"]
    depends_on:
      - db 
      - server

  server:
    image: server-img
    container_name: server-cont
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    env_file:
      - path: ./server/.env
        required: true
    environment:
      DATABASE: postgres
      DATABASE_URL: postgresql://admin:admin@db:5432
    restart: unless-stopped 
    command: python3 manage.py run -h 0.0.0.0
    networks:
      - flask_vue_network
    depends_on:
      - db
    stdin_open: true
    tty: true  

  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - flask_vue_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes: 
      - flask_vue_data:/var/lib/postgresql/data

networks:
  flask_vue_network:
    driver: bridge
volumes:
  flask_vue_data:
    driver: local
