services:
  vue-app:
    container_name: vue-prod-cont
    build:
      context: ./client
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "8000:80"
    networks:
      - flask_vue
    depends_on:
      - db
      - server

  db:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    container_name: server-app
    restart: unless-stopped
    env_file:
      - ./server/.env.prod
    command: gunicorn 


networks:
  flask_vue:
    driver: bridge
